name: Code Quality
on:
  push:
    branches: 
      - master
      - main
  pull_request:
jobs:
  lint:
    name: super-lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v3
      - name: Lint Code Base
        uses: github/super-linter@slim-v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_NATURAL_LANGUAGE: false